// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"HalfMove","status":true,"description":"半歩移動プラグイン","parameters":{"8方向移動":"true","8方向移動スイッチ":"0","イベントすり抜け":"false","強制中無効":"false","角回避":"true","斜め移動中減速":"false","トリガー拡大":"false","実歩数調整":"false","上半分移動不可地形":"0","上半分移動不可Region":"0","下半分移動不可地形":"0","下半分移動不可Region":"0","右半分移動不可地形":"0","右半分移動不可Region":"0","左半分移動不可地形":"0","左半分移動不可Region":"0","全方向移動不可地形":"0","全方向移動不可Region":"0","イベント複数起動防止":"false","イベント位置重複OK":"false"}},
{"name":"LN_AdvancedMapPuzzleSystem","status":true,"description":"謎解きマップシステムプラグイン v0.1.0","parameters":{}},
{"name":"LN_AdvancedMapPuzzleSystem_MapSkill","status":false,"description":"謎解きマップシステムプラグイン v0.1.0","parameters":{}}
];
